

model:
  provider:
    type: huggingface
  model_name: deepseek/deepseek-r1-0528-qwen3-8b
  region: us-east-1
  credentials:
    api_base: ${HF_API_BASE_DEEPSEEK_QWEN_8B}
    api_key: ${HF_TOKEN}
include:
  - "src"
exclude:
  - ".venv"
  - "test-codebase"
  - "**/__pycache__/"
  - "**/*.pyc"
  - "**/*.egg-info/"
  - "**/.pytest_cache/"
score_threshold: 80
