

model:
  provider:
    type: huggingface
  model_name: google/gemma-3-27b-it-fast
  region: us-east-1
  credentials:
    api_base: ${HF_API_BASE_GEMMA3}
    api_key: ${HF_TOKEN}
include:
  - "src"
exclude:
  - ".venv"
  - "test-codebase"
  - "**/__pycache__/"
  - "**/*.pyc"
  - "**/*.egg-info/"
  - "**/.pytest_cache/"
score_threshold: 80
