name: "AI Code Review Agent"
description: "Run GenAI-powered code reviews using a Python-based CLI"
author: "Manav Khandurie"

inputs:
  config-path:
    description: "Path to the YAML config file"
    required: true
  score-threshold:
    description: "Override score threshold"
    required: false

runs:
  using: "docker"
  image: "docker://manavkhandurie/code-review-agent:v1.1.0"
  args:
    - "--config"
    - ${{ inputs.config-path }}
    - "--score-threshold"
    - ${{ inputs.score-threshold }}
