name: "AI Code Review Agent"
description: "Run GenAI-powered code reviews using a Python-based CLI"
author: "Manav Khandurie"

inputs:
  config-path:
    description: "Path to the YAML config file"
    required: true
  score-threshold:
    description: "Override score threshold"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "--config"
    - ${{ inputs.config-path }}
    - "--score-threshold"
    - ${{ inputs.score-threshold }}
  env:
    DEEPSEEK_API_KEY: ${{ env.DEEPSEEK_API_KEY }}
    AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: ${{ env.AWS_REGION }}
