name: "Issue Agent"
description: "Runs the autonomous issue agent"

inputs:
  src:
    description: "Source paths to analyze"
    required: false
    default: "./data/"
  provider:
    description: "LLM provider (e.g., deepseek)"
    required: true
  model_name:
    description: "LLM model name"
    required: true
  api_key:
    description: "API key for the LLM"
    required: true
  api_base:
    description: "Optional base URL for the LLM"
    required: false
    default: ""
  github_token:
    description: "GitHub token used inside the container (for creating/fetching issues)"
    required: true
  github_repo:
    description: "GitHub repo slug (e.g., user/repo) passed to the agent"
    required: true
  skip_yaml:
    description: "Skip YAML config loading (true/false)"
    required: false
    default: "true"

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    GITHUB_REPO: ${{ inputs.github_repo }}
  args:
    - "--src=${{ inputs.src }}"
    - "--provider=${{ inputs.provider }}"
    - "--model_name=${{ inputs.model_name }}"
    - "--api_key=${{ inputs.api_key }}"
    - "--api_base=${{ inputs.api_base }}"
    - "--skip-yaml=${{ inputs.skip_yaml }}"
