models:
  # - type: openai
  #   params:
  #     temperature: 1.0
  #     model_name: gpt-4o-mini
  #     openai_api_key: ${OPENAI_API_KEY}

  - type: deepseek
    params:
      temperature: 0.3
      model_name: deepseek-chat
      openai_api_key: ${DEEPSEEK_API_KEY}
      openai_api_base: https://api.deepseek.com
