name: AI Code Review

on: [push, pull_request]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run AI Code Review Agent
        uses: ./code-review-agent
        with:
          config-path: "code-review-agent/ex-configs/deepseek-config.yaml"
          score-threshold: 75
        env:
          OPENAI_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }} 
